version: "3.9"
services:
  db:
    image: postgres:16
    container_name: apple_api_db
    environment:
      POSTGRES_DB: apple_api
      POSTGRES_USER: apple
      POSTGRES_PASSWORD: applepwd
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U apple -d apple_api"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: apple_api_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      APPLE_API_PROFILE: prod
      APPLE_API_DB_URL: jdbc:postgresql://db:5432/apple_api
      APPLE_API_DB_USERNAME: apple
      APPLE_API_DB_PASSWORD: applepwd
      APPLE_API_JWT_SECRET: change_this_in_prod
      # Opcional: tunning Hikari
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 10
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 3000
      SPRING_DATASOURCE_HIKARI_VALIDATION_TIMEOUT: 1000
      # Ajuste memória se necessário
      JAVA_OPTS: "-Xms256m -Xmx512m"
    ports:
      - "8083:8083"

volumes:
  dbdata: